services:
  - type: web
    name: sms-verification-gateway
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: off
    maxShutdownDelaySeconds: 30
    envVars:
      - key: GATEWAY_PHONE_NUMBER
        sync: false
      - key: API_HMAC_SECRET
        sync: false
      - key: SMS_FORWARDER_HMAC_SECRET
        sync: false
      - key: DEFAULT_COUNTRY_CODE
        value: "62"
      - key: VERIFICATION_PREFIX
        value: VERIF
      - key: VERIFICATION_CODE_LENGTH
        value: "8"
      - key: VERIFICATION_TTL
        value: PT10M
      - key: HMAC_ALLOWED_CLOCK_SKEW
        value: PT5M
